var/global/list/reagent_sheets = list( // Recompressing reagents back into sheets
	REAGENT_ID_COPPER 			= MAT_COPPER,
	REAGENT_ID_TIN 				= MAT_TIN,
	REAGENT_ID_WOODPULP 		= MAT_CARDBOARD,
	REAGENT_ID_CARBON 			= MAT_GRAPHITE,
	REAGENT_ID_ALUMINIUM 		= MAT_ALUMINIUM,
	REAGENT_ID_TITANIUM 		= MAT_TITANIUM,
	REAGENT_ID_IRON 			= MAT_IRON,
	REAGENT_ID_LEAD				= MAT_LEAD,
	REAGENT_ID_URANIUM			= MAT_URANIUM,
	REAGENT_ID_PHORON 			= MAT_PHORON,
	REAGENT_ID_GOLD 			= MAT_GOLD,
	REAGENT_ID_SILVER 			= MAT_SILVER,
	REAGENT_ID_PLATINUM			= MAT_PLATINUM,
	REAGENT_ID_SILICON 			= MAT_GLASS,
	// Mostly harmless
	REAGENT_ID_PROTEIN			= "FLAG_SMOKE",
	REAGENT_ID_TRIGLYCERIDE 	= "FLAG_SMOKE",
	REAGENT_ID_SODIUM	 		= "FLAG_SMOKE",
	REAGENT_ID_PHOSPHORUS 		= "FLAG_SMOKE",
	REAGENT_ID_ETHANOL 			= "FLAG_SMOKE",
	// Extremely stupid ones
	REAGENT_ID_OXYGEN 			= "FLAG_EXPLODE",
	REAGENT_ID_HYDROGEN 		= "FLAG_EXPLODE",
	REAGENT_ID_SUPERMATTER 		= "FLAG_EXPLODE",
	// Nothing is funnier to me
	REAGENT_ID_SPIDEREGG 		= "FLAG_SPIDERS"
	)
