#define BADOBJ name = "BAD OBJ";icon = 'icons/obj/storage_vr.dmi';icon_state = "";

/obj/effect/shuttle_landmark/southern_cross/supply_offsite
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/supply_station
	BADOBJ
/obj/machinery/computer/shuttle_control/multi/administration
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/admin_offsite
	BADOBJ
/obj/machinery/computer/shuttle_control/multi/centcomBADOBJ
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/transport1_offsite
	BADOBJ
/obj/machinery/computer/shuttle_control/multi/merchant
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/merchant_offsite
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/escape/offsite
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/arrivals_offsite
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/arrivals_station
	BADOBJ
/obj/machinery/computer/shuttle_control/exploration
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/sling_station
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/sling_outpost
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/carrier
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/carrier/hangar_one
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/carrier/baby_mammoth_dock
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/carrier/ursula_dock
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/carrier/stargazer_dock
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/carrier/needle_dock
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/carrier/echidna_dock
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/carrier/port_dock
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/carrier/starboard_dock
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/escape/station
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/escape/transit
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/cryostorage_station
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/cryostorage_offsite
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/cryostorage_transit
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/large_escape_pod1/station
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/large_escape_pod1/offsite
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/large_escape_pod1/transit
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/large_escape_pod2/station
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/large_escape_pod2/offsite
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/large_escape_pod2/transit
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/large_escape_pod3/station
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/large_escape_pod3/offsite
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/large_escape_pod3/transit
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/large_escape_pod4/station
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/large_escape_pod4/offsite
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/large_escape_pod4/transit
	BADOBJ
/obj/effect/shuttle_landmark/relicbase/arrivals/offsite
	BADOBJ
/obj/effect/shuttle_landmark/relicbase/arrivals/station
	BADOBJ
/obj/effect/shuttle_landmark/relicbase/escape/offsite
	BADOBJ
/obj/effect/shuttle_landmark/relicbase/escape/station
	BADOBJ
/obj/effect/shuttle_landmark/relicbase/escape/transit
	BADOBJ
/obj/effect/shuttle_landmark/relicbase/mining_base
	BADOBJ
/obj/effect/shuttle_landmark/relicbase/mining_undermines
	BADOBJ
/obj/effect/shuttle_landmark/relicbase/research
	BADOBJ
/obj/effect/shuttle_landmark/relicbase/research_undermines
	BADOBJ

/obj/structure/backup_implanter_ch
	BADOBJ
/obj/item/storage/box/backup_kit
	BADOBJ
/obj/item/storage/box/nifsofts_medical
	BADOBJ
/obj/structure/noticeboard/airlock
	BADOBJ
/obj/item/storage/box/nifsofts_engineering
	BADOBJ
/obj/item/storage/box/nifsofts_security
	BADOBJ

/turf/simulated/floor/outdoors/grass/sif/cave
	BADOBJ
/turf/simulated/floor/outdoors/grass/sif/valley/edge
	BADOBJ
/turf/simulated/floor/outdoors/grass/sif/valley
	BADOBJ


/obj/machinery/cash_register/command
	BADOBJ

/obj/machinery/cash_register/medical
	BADOBJ

/obj/machinery/cash_register/engineering
	BADOBJ

/obj/machinery/cash_register/science
	BADOBJ

/obj/machinery/cash_register/security
	BADOBJ

/obj/machinery/cash_register/cargo
	BADOBJ

/obj/machinery/cash_register/civilian
	BADOBJ

/obj/effect/landmark/darkspawn
	BADOBJ
/obj/machinery/computer/shuttle_control/multi/centcom
	BADOBJ
/obj/machinery/lapvend
	BADOBJ
/obj/item/retail_scanner/civilian
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/escape_pod1/offsite
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/escape_pod2/offsite
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/escape_pod3/offsite
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/escape_pod4/offsite
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/escape_pod5/offsite
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/escape_pod6/offsite
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/escape_pod7/offsite
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/escape_pod8/offsite
	BADOBJ
/obj/machinery/computer/shuttle_control/multi/heist
	BADOBJ
/obj/machinery/computer/shuttle_control/multi/ert
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/escape_pod1/station
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/escape_pod2/station
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/escape_pod3/station
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/escape_pod4/station
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/escape_pod5/station
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/escape_pod6/station
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/escape_pod7/station
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/escape_pod8/station
	BADOBJ

/obj/effect/shuttle_landmark/southern_cross/escape_pod1/transit
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/escape_pod2/transit
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/escape_pod3/transit
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/escape_pod4/transit
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/escape_pod5/transit
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/escape_pod6/transit
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/escape_pod7/transit
	BADOBJ
/obj/effect/shuttle_landmark/southern_cross/escape_pod8/transit
	BADOBJ

#undef BADOBJ
