/datum/sop_entry/expectations
	title = "Crew Expectations"
	author = "E-Shui Official"
	body = 	{"When on board any station, there are expectations that come with crew jobs based on their role, and their experience. These are the expectations from corporate E-Shui's standards and viewings, and a crewmember may have greater, or lesser, expectations held upon them by their chief of staff.
			<hr><b>All Crew</b><hr>
			E-Shui's motto is "Safety Third": While this motto may sound hazardous or confusing, this does not mean safety comes third in any numbered list. It should instead be a state of mind enforced by all crew. If safety is first, no risks are taken and no tasks are completed. Rescuing crew from a hazardous situation, repairing damages, operating the station, and all other tasks are all innately hazardous cannot be completed if safety is prime. Nobody on the station is responsible for your safety: Medical is to provide critical treatment when your lack of safety preparation has made itself known. Security is to provide defense and safety of the station itself, and the crew within; but they can not be ever present, especially should you put yourself willfully into a dangerous situation.
			<br>
			<hr><b>Command:</b><hr>
			The command team is generally required to stay on station at all times. They are not to embark on 'away missions', 'expeditions', 'maintenance diving' or other risky activities that take them away from the station. Doing so is considered a misuse of their time, and an unjustifiable risk to their position and rank, unless they are the sole individual capable of the task.
			<br><br><b>The Captain</b> is responsible for maintaining order on the station, delegating tasks to the heads of staff, and ensuring communication between the heads of staff is appropriate. The Captain is not to perform duties of any department other than command on station, even in a crisis. Their role is to maintain order, and trust their heads of staff to run the station as necessary, and to fill in any missing gaps as necessary. EX: if there is no Head of Security, during a crisis the captain is expected to act as the HoS.
			<br><br><b>The Command Secretary</b> (also known as Command Secretary, or Executive Officer) is a flexible position. Acting as a liaison and final word when there's an argument between heads of staff, having near final say on SoP direction and interpretation, acting judge on the station, and resolving inter-department conflicts with staff. They can change crewmember IDs as necessary and are responsible for maintaining and verifying employment records of staff. With a captain present they can be tasked to act in their stead to carry out tasks for the function of the station while the captain operates in filling in another head's position.
			<br><br><b>Science officers</b> are expected to coordinate and encourage the generation of research points across the other departments, and guide and teach newer staff to the risky areas of research, as marked by checkered purple floor markings. Science officers are not expected to perform the research tasks themselves. These jobs include: Genetics, Xenobiology, Xenoarcheology, Anomaly Harvesting, Phoronics, and Xenobotany.
			<br>
			<hr><b>Medical:</b><hr>
			Medical staff are expected to assist the station crew in staying alive, filling prescriptions, noting medical records, and resleeving the crew too far gone, or already deceased. They are expected to have an understanding of medical Triage, and at bare minimum basic treatment knowledge. They are expected to understand that the resleever is expensive and is a last resort on treatment, not a lazy cure-all, and the legality of using it.
			It is noted to remember that triage is in order of injury, not order of command. The captain with a papercut is a lower priority than a station guest missing a leg.
			<br><br><b>The Chief Medical Officer</b> is expected to have at least moderate understanding of every medical field; surgery, chemistry, treatment, resleeving, alien crew anatomy and treatment. They are required to have a thorough understanding of patient's rights, triage, and at least two areas of medical. They delegate the doctors under them, take charge during a violet-level event, and if needed, can step in to aid their doctors in any violet-level event. They are encouraged to know how to drive a tank.
			<br><br><b>Doctors and Surgeons</b> are expected to have a thorough understanding of triage, and patient stabilization. They are expected to be able to treat any major or minor injury they come across in normal day to day operations. Doctors includes specializations such as Chemists and Surgeons, who are expected to know their field, as well as general treatment. General doctors are not expected to have a thorough understanding of surgery or chemistry, but are recommended to study and learn at convenience.
			<br><br><b>Paramedics</b> are expected to know patient stabilization, proper medical practice, and have a thorough understanding of the environmental hazards of the Outpost-21 grounds. Their job entails rescuing, and stabilizing all injured crewmembers in order of triage, not by order of chain of command. They are not expected to understand full medical duties of stabilized patients moving to long term treatment.
			<br><br><b>Psychologists</b> are expected to have a thorough and deep understanding of social skills and patient mental health. They are not expected to know further medical knowledge, and are not expected to assist medical during a medical crisis, instead focusing on keeping crew calm and orderly.
			<br><br><b>Specialist doctors</b>: Such as Xenoanatomy Specialists, Geneticists, Virologists, etc, are required to have a thorough understanding of their field, and to be able to fill requirements of a general practitioning doctor; not requiring to have significant understanding outside their expertise.
			<br>
			<hr><b>Security:</b><hr>
			Security is expected to have a thorough understanding of corporate law, crew rights, and condition codes. They are expected to have a moderate understanding of weapon usage, but a thorough understanding of nonlethally subduing suspects. Their role on the station is to maintain order and peace. Enforce station safety, and act as the guiding arm in a crisis to ensure as many crew survive as possible, and threats are dealt with with the least amount of force necessary. Security should protect, in order: The Terraformer, The Station, Any Sensitive Information, The Station Crew, The Station AI, Any Guests.
			<br><br><b>The Head of Security</b> is expected to have a thorough understanding of corporate law, and strong leadership skills. They are required to be able to operate any weapon in the green and blue armories, most weapons in the Red armory, proper armor choice, and are required to know how to drive a tank. They are responsible for leading security, issuing weapon permits to non-security crew as needed.
			<br><br><b>The Warden</b> is in charge of the brig, maintaining prisoners, managing sentences. The warden is expected to have a thorough understanding of corporate skills, and know how to operate any weapon in the red and blue armories. They are expected to train lower level security personnel in experienced weapon usage, and make regular checks to the brig to ensure escape is not possible.
			<br><br><b>Security Officers</b> are the arm of the warden and head of security. They are expected to patrol the station, maintain vigilance, and ensure station order. They are expected to have a moderate understanding of corporate law, and capability in nonlethal target subduing. They are required to know how to operate a stun baton and tazer.
			<br><br><b>Detectives</b> are in charge of analyzing crime scenes. They are the arm of a warden, and the lowest in the chain of command of security. They are not expected to enforce station law, make arrests, or subdue criminals. They are expected to have a moderate to thorough understanding of their tools for crime scene analysis, a thorough understanding of corporate law, and a moderate understanding of their firearm.
			<br><br><b>Security medics</b> follow standard chain of command, with HoS being a higher priority than the CMO. They report to security for operational tasks and primary duties, and while authorized to be in medical, are expected to not drain medical supplies excessively. They are expected to assist in keeping officers alive above all other patients, and are not authorized to make arrests aside from medical arrests. They are expected to have decent knowledge of hand to hand combat.
			<br><br><b>Penetration Testers</b> are expected to have excellent survival skills, and solo operation capability. They must have proficiency in self treatment first aid. They should have Survival, Concealment, Resistance, Escape, and Evasion capability beyond a beginner level. They are not expected to serve and defend the station; only the terraformer; however they can not expect any assistance from the station. They are expected to utilize extreme lethality against all hostile forces they may encounter on station grounds; outside of the primary facility. They are expected to utilize their skills to attempt forced entry into the station, minimizing crew harm, to better train station crew to combat hostile infiltrators, and to reveal exploits in station defenses.
			<br>
			<br><hr><b>Engineering:</b><hr>
			Engineering crew is expected to be able to repair any damaged section of the station, start the main engine, operate the backup incinerator, and operate the solar backup array. They are expected to know the locations of backup generators, and know safety precautions with live wires, and basic understanding of atmospherics.
			<br><br><b>The Chief Engineer</b> is expected to have deep understanding of every aspect of engineering, as well as leadership skills. They are expected to be able to manage critical repairs during an orange-level event. They are expected to understand proper RCON management, and the power requirements of every department, and the prioritizing of which departments are in need of repairs first should multiple departments get damaged. They are expected to have deep understanding of hazardous atmospheric conditions, and terraformer safety. They are expected to have a basic understanding of the following engineering research related tasks: particle smashing, anomalies, and circuitry. During AI related emergencies, the Chief Engineer is expected to resolve errant AI laws.
			<br><br><b>Engineers</b> are expected to have a good understanding of construction, repairs, safety in hazardous atmospheres, and repairs to most station infrastructure. They are expected to know proper safety with live wires, and operation of the station's power sources. They are not expected to have a deep understanding of atmospherics.
			<br><br><b>Atmospheric Technicians</b> are expected to have a thorough understanding of the station's atmospherics supply, power draw, gas mixing. They are expected to understand safe procedures for operating within the Terraformer, and how to operate in environments with exceedingly hazardous atmospheric conditions. They are not expected to have a deep understanding of engine power supply operations, and are expected to have only a moderate understanding of station repair.
			<br><br><b>Roboticists</b> are expected to have a thorough understanding of circuitry, robot repair and full body prosthetic repair. They are not expected to perform engine setup or atmospherics tasks. They are still expected to repair damage to the station when no other engineers are present.
			<br><br><b>Anomalists</b> are expected to contain and harvest anomalies as they appear. Anomalist is a research-adjacent department; and thus produces research points and materials for use by all other departments. Anomalists are expected to repair the damage caused by station affecting anomalies during their containment, or the failure thereof.
			<br>
			<hr><b>Cargo:</b><hr>
			Cargo is responsible for supplying the station with various supplies to continue operations and morale. From ordered supplies from E-shui main, or from mined resources from the reclamation yard.
			<br><b>The Quartermaster</b> leads cargo and the civilian department, they are expected to have a thorough understanding of all of cargo's departments: Mining, and Freight, and a moderate understanding of the needs of the civilian departments; such as the kitchen and bar. While under most stations they fall under the head of personnel, under E-shui law they are classified as a head of staff themselves, though the lowest head in the chain of command. They are responsible for the productivity of cargo, and to assist in any areas cargo is lacking. The Quatertmaster is expected to have a basic understanding of the following cargo research related tasks: xenohusbandry(also known as xenobiology or slimes), and xenoarcheology.
			<br><b>Miners</b> are expected to know proper EVA procedures, operation in a null-G and vacuum. They are expected to know how to operate all mining equipment, and how to fly the supplied mining trawler to access the reclamation yard. They are expected to know efficient operation of the ore processor for common materials. Miners are highly encouraged to gain familiarity with common xenoarcheological finds, but are not expected to have more than basic artifact safety knowledge.
			<br><b>Cargo Technicians</b> are expected to know the ordering procedures of the station, and have at least a moderate understanding of department required goods to prevent waste and misuse of controlled cargo. They are expected to know the station layout for manual delivery, and operation of the disposal mail system. They are expected to know the location of the incinerator for trash disposal.
			<br><b>Xenoarcheologists</b> are specialized miners, and have all the expectations of a miner. Their additional responsibilities include a deep understanding of xenoarcheological finds, and their exotic properties. They are expected to safely contain or destroy dangerous artifacts, and harvest or facilitate the use of beneficial artifacts. They are expected to generate research points through the destructive analysis of artifacts.
			<br><b>Xenobiologists</b> are expected to have a deep understand of slime care, breeding, and harvesting. They are responsible for safely containing multiple slimes, and managing the various safety systems used to prevent a slime outbreak. They are responsible for generating research or supply points through the destructive analysis, or selling of slime cores. They are expected to provide the benefits of specific breeds of slimes, or their harvested products, to the rest of the crew. If cargo technicians are not present, xenobiologists are expected to handle cargo technician duties.
			<br><b>Janitors</b> are expected to maintain the cleanliness of the station, and to have a moderate understanding of the station layout. Signage must be placed near floors prior to mopping.
			<br>
			<hr><b>Civilian:</b><hr>
			Civilian departments are expected to have general understanding of their chosen task, and their expectations during various condition codes, and to have a basic understanding of the chain of command. But are not expected to perform any extravagant tasks, or expected to have any extravagant knowledge.
			<br><b>Chefs, Bartenders, and Botanists</b> are expected to provide the nourishment for the crew. While each one is specialized to their individual task, be it serving drinks, cooking food, or growing ingredients, they are expected to have a minimal understanding of the other areas of their shared department, and to have a moderate understanding of their specialized profession.
			<br><b>Chaplains</b> are expected to have a strong understanding of their faith, and good interpersonal skills, acting as a therapist if there is no psychiatrist. They are expected to respond and deal with a station crisis involving a cult or the supernatural to the best of their ability.
			<br><b>Librarians</b> are expected to keep the library stocked with appropriate books, and to assist any off-station journalists. They are expected to have a thorough understanding of the station's layout and to give tours to new members of the station. They are required to be able to read and write legibly.
			<br><b>Interns and Station Guests</b> are expected to understand the environmental hazards of the station.
			<br>
			<hr><b>Station AI and Synthetics:</b><hr>
			The Station AI is bound to its laws, and to the crew. It is the lowest on the chain of command, and cannot give orders. It is to aid the crew with door access in any way they deem necessary for their station operations, according to their chain of command, corporate law, and station condition code.
			<br><b>Lawed Synthetics</b>, to include: any mobile artificial intelligence, cyborgs, 'dogborgs' and other such machines; are under the service of the station AI, and their own laws, to be synced with station AI's law on arrival. They act as mobile door openers, and follow the specialized functionality of their chassis. They are not expected to serve any function beyond their specialization, according to the crew's chain of command and station condition code."}
