// Heavily modified port of https://github.com/Bubberstation/Bubberstation/blob/b6dbca4ef6bbf4601b8e752176376166025c8d60/modular_zubbers/code/modules/blooper/bark_list.dm
// Bubbers uses actual voice datums! We uses ugly global lists inside another assoc list. This felt sinful to make.

GLOBAL_LIST_INIT(bubber_speak_mutedc2,list('sound/instruments/synthesis_samples/guitar/crisis_muted/C2.ogg'))
GLOBAL_LIST_INIT(bubber_speak_mutedc3,list('sound/instruments/synthesis_samples/guitar/crisis_muted/C3.ogg'))
GLOBAL_LIST_INIT(bubber_speak_mutedc4,list('sound/instruments/synthesis_samples/guitar/crisis_muted/C4.ogg'))
GLOBAL_LIST_INIT(bubber_speak_banjoc3,list('sound/instruments/banjo/Cn3.ogg'))
GLOBAL_LIST_INIT(bubber_speak_banjoc4,list('sound/instruments/banjo/Cn4.ogg'))
GLOBAL_LIST_INIT(bubber_speak_squeaky,list('modular_zubbers/sound/items/toy_squeak/toysqueak1.ogg'))
GLOBAL_LIST_INIT(bubber_speak_chitter,list('modular_zubbers/code/modules/blooper/voice/bloopers/chitter.ogg'))
GLOBAL_LIST_INIT(bubber_speak_synthetic_grunt,list('sound/misc/bloop.ogg'))
GLOBAL_LIST_INIT(bubber_speak_synthetic,list('modular_zubbers/sound/machines/uplink/uplinkerror.ogg'))
GLOBAL_LIST_INIT(bubber_speak_bullet,list('modular_zubbers/sound/items/weapons/bulletflyby.ogg'))
GLOBAL_LIST_INIT(bubber_speak_coggers,list('modular_zubbers/sound/machines/clockcult/integration_cog_install.ogg'))
GLOBAL_LIST_INIT(bubber_speak_moff_short,list('modular_zubbers/code/modules/blooper/voice/bloopers/mothsqueak.ogg'))
GLOBAL_LIST_INIT(bubber_speak_meow,list('modular_zubbers/code/modules/blooper/voice/bloopers/meow1.ogg'))
GLOBAL_LIST_INIT(bubber_speak_chirp,list('modular_zubbers/code/modules/blooper/voice/bloopers/chirp.ogg'))
GLOBAL_LIST_INIT(bubber_speak_caw,list('modular_zubbers/code/modules/blooper/voice/bloopers/caw.ogg'))
GLOBAL_LIST_INIT(bubber_speak_chitter_alt,list('modular_zubbers/code/modules/blooper/voice/bloopers/moth/mothchitter2.ogg'))
// Undertale
GLOBAL_LIST_INIT(bubber_speak_alphys,list('modular_zubbers/code/modules/blooper/voice/bloopers/undertale/voice_alphys.ogg'))
GLOBAL_LIST_INIT(bubber_speak_asgore,list('modular_zubbers/code/modules/blooper/voice/bloopers/undertale/voice_asgore.ogg'))
GLOBAL_LIST_INIT(bubber_speak_flowey,list('modular_zubbers/code/modules/blooper/voice/bloopers/undertale/voice_flowey_1.ogg'))
GLOBAL_LIST_INIT(bubber_speak_flowey_evil,list('modular_zubbers/code/modules/blooper/voice/bloopers/undertale/voice_flowey_2.ogg'))
GLOBAL_LIST_INIT(bubber_speak_papyrus,list('modular_zubbers/code/modules/blooper/voice/bloopers/undertale/voice_papyrus.ogg'))
GLOBAL_LIST_INIT(bubber_speak_ralsei,list('modular_zubbers/code/modules/blooper/voice/bloopers/undertale/voice_ralsei.ogg'))
GLOBAL_LIST_INIT(bubber_speak_sans,list('modular_zubbers/code/modules/blooper/voice/bloopers/undertale/voice_sans.ogg'))
GLOBAL_LIST_INIT(bubber_speak_toriel,list('modular_zubbers/code/modules/blooper/voice/bloopers/undertale/voice_toriel.ogg'))
GLOBAL_LIST_INIT(bubber_speak_undyne,list('modular_zubbers/code/modules/blooper/voice/bloopers/undertale/voice_undyne.ogg'))
GLOBAL_LIST_INIT(bubber_speak_temmie,list('modular_zubbers/code/modules/blooper/voice/bloopers/undertale/voice_temmie.ogg'))
GLOBAL_LIST_INIT(bubber_speak_susie,list('modular_zubbers/code/modules/blooper/voice/bloopers/undertale/voice_susie.ogg'))
GLOBAL_LIST_INIT(bubber_speak_gaster,list('modular_zubbers/code/modules/blooper/voice/bloopers/undertale/voice_gaster_1.ogg'))
GLOBAL_LIST_INIT(bubber_speak_mettaton,list('modular_zubbers/code/modules/blooper/voice/bloopers/undertale/voice_metta_1.ogg'))
GLOBAL_LIST_INIT(bubber_speak_gen_monster,list('modular_zubbers/code/modules/blooper/voice/bloopers/undertale/voice_monster1.ogg'))
GLOBAL_LIST_INIT(bubber_speak_gen_monster_alt2,list('modular_zubbers/code/modules/blooper/voice/bloopers/undertale/voice_monster2.ogg'))
// Don't starve
GLOBAL_LIST_INIT(bubber_speak_wilson,list('modular_zubbers/code/modules/blooper/voice/bloopers/dont_starve/wilson_blooper.ogg'))
GLOBAL_LIST_INIT(bubber_speak_wolfgang,list('modular_zubbers/code/modules/blooper/voice/bloopers/dont_starve/wolfgang_blooper.ogg'))
GLOBAL_LIST_INIT(bubber_speak_woodie,list('modular_zubbers/code/modules/blooper/voice/bloopers/dont_starve/woodie_blooper.ogg'))
GLOBAL_LIST_INIT(bubber_speak_wurt,list('modular_zubbers/code/modules/blooper/voice/bloopers/dont_starve/wurt_blooper.ogg'))
GLOBAL_LIST_INIT(bubber_speak_wx78,list('modular_zubbers/code/modules/blooper/voice/bloopers/dont_starve/wx78_blooper.ogg'))
// Kazooie
GLOBAL_LIST_INIT(bubber_speak_whistle,list('modular_zubbers/code/modules/blooper/voice/bloopers/kazooie/birdwhistle.ogg'))
GLOBAL_LIST_INIT(bubber_speak_whistle_alt,list('modular_zubbers/code/modules/blooper/voice/bloopers/kazooie/birdwhistle2.ogg'))
GLOBAL_LIST_INIT(bubber_speak_caw_alt,list('modular_zubbers/code/modules/blooper/voice/bloopers/kazooie/caw.ogg'))
GLOBAL_LIST_INIT(bubber_speak_caw_alt2,list('modular_zubbers/code/modules/blooper/voice/bloopers/kazooie/caw2.ogg'))
GLOBAL_LIST_INIT(bubber_speak_caw_alt3,list('modular_zubbers/code/modules/blooper/voice/bloopers/kazooie/caw3.ogg'))
GLOBAL_LIST_INIT(bubber_speak_ehh,list('modular_zubbers/code/modules/blooper/voice/bloopers/kazooie/ehh.ogg'))
GLOBAL_LIST_INIT(bubber_speak_ehh_alt,list('modular_zubbers/code/modules/blooper/voice/bloopers/kazooie/ehh2.ogg'))
GLOBAL_LIST_INIT(bubber_speak_ehh_alt2,list('modular_zubbers/code/modules/blooper/voice/bloopers/kazooie/ehh3.ogg'))
GLOBAL_LIST_INIT(bubber_speak_ehh_alt3,list('modular_zubbers/code/modules/blooper/voice/bloopers/kazooie/ehh4.ogg'))
GLOBAL_LIST_INIT(bubber_speak_ehh_alt4,list('modular_zubbers/code/modules/blooper/voice/bloopers/kazooie/ehh5.ogg'))
GLOBAL_LIST_INIT(bubber_speak_faucet,list('modular_zubbers/code/modules/blooper/voice/bloopers/kazooie/faucet.ogg'))
GLOBAL_LIST_INIT(bubber_speak_faucet_alt,list('modular_zubbers/code/modules/blooper/voice/bloopers/kazooie/faucet2.ogg'))
GLOBAL_LIST_INIT(bubber_speak_ribbit,list('modular_zubbers/code/modules/blooper/voice/bloopers/kazooie/ribbit.ogg'))
GLOBAL_LIST_INIT(bubber_speak_hoot,list('modular_zubbers/code/modules/blooper/voice/bloopers/kazooie/hoot.ogg'))
GLOBAL_LIST_INIT(bubber_speak_tweet,list('modular_zubbers/code/modules/blooper/voice/bloopers/kazooie/tweet.ogg'))
GLOBAL_LIST_INIT(bubber_speak_dwoop,list('modular_zubbers/code/modules/blooper/voice/bloopers/kazooie/dwoop.ogg'))
GLOBAL_LIST_INIT(bubber_speak_uhm,list('modular_zubbers/code/modules/blooper/voice/bloopers/kazooie/uhm.ogg'))
GLOBAL_LIST_INIT(bubber_speak_wurtesh,list('modular_zubbers/code/modules/blooper/voice/bloopers/kazooie/wurble1.ogg'))
GLOBAL_LIST_INIT(bubber_speak_chitter2,list('modular_zubbers/code/modules/blooper/voice/bloopers/kazooie/chitter1.ogg'))
